# Cleaning f1db data

This notebook is to clean the series of csv tables coming from the [Ergast Developer API](https://ergast.com/mrd/db/). I'm downloading the raw csv tables and processing them here.

Some things to note about the data:

* The data is not chronologically organized in the csv case. Race numbering starts with 1 corresponding to 2007's first race, and then goes back at a point to fill in the 1950â€“2006 data and also add in the data moving forward.
* In the standings table, a new entry is not added after a race if the driver does not change standings.
* When a cell is `\N` it means the cell is null, or the value wasn't recorded. This largely applies to things for which we had no data in the beginning.
* Looking at the original `raceId`, something happened because Azerbaijan GP 2019 was the 1001st race but their id for the same race was 1013. I assume the counting was pushed ahead somewhere in the middle, but things are still okay.
* The `drivers` table is actually named `driver.csv`.


**I last downloaded this data on 19-06-10.**

In [1]:
import pandas as pd
import numpy as np

## [01] Add headers to the csv tables

First thing we'll do is add headers to each table based on this [schema text file](http://ergast.com/schemas/f1db_schema.txt). I will also couple removing the `\N` characters in this step.

In [2]:
baseurl = "../data/f1db_csv/"
destination = "../data/source/"

#names correspond to the csv files and not the table names given at the top of the schema text file
tables = ["circuits", "constructor_results", "constructor_standings", "constructors", "driver_standings", 
          "driver", "lap_times", "pit_stops", "qualifying", "races", "results", "seasons", "status"]

# all the headers are grouped by table and put into one big list
headers = [["circuitId", "circuitRef", "name", "location", "country","lat", "lng", "alt", "url"], #circuits
          ["constructorResultsId", "raceId", "constructorId", "points", "status"], #constructor_results
          ["constructorStandingsId", "constructorId", "points", "position", "positionText", "wins"], #constructor_standings
          ["constructorId", "constructorRef", "name", "nationality", "url"], #constructors
          ["driverStandingsId", "raceId", "driverId", "points", "position", "positionText", "wins"], #driver_standings
          ["driverId", "driverRef", "number", "code", "forename", "surname", "dob", "nationality", "url" ], #drivers
          ["raceId", "driverId", "lap", "position", "time", "milliseconds"], #lap_times
          ["raceId", "driverId", "stop", "lap", "time", "duration", "milliseconds"], #pit_stops
          ["qualifyId", "raceId", "driverId", "constructorId", "number",
           "position", "q1", "q2","q3"], #qualifying
          ["raceId", "year", "round", "circuitId", "name", "date", "time", "url"], #races
          ["resultId", "raceId", "driverId", "constructorId", "number", "grid", "position",
           "positionText", "positionOrder", "points", "laps", "time", "milliseconds",
           "fastestLap", "rank", "fastestLapTime", "fastestLapSpeed", "statusId"], #results
          ["year","url"], #seasons
          ["statusId", "status"] #status
          ]

for i in range(len(tables)):
    #pick the right table name and the right header
    table = tables[i]
    header = headers[i]
    
    #import the csv file associated with the table and add in the header to it
    df = pd.read_csv(baseurl+table+".csv",names=header)
    #get rid of the null characters
    df = df.replace("\\N","")
    #export back to a csv in the working folder
    df.to_csv(destination+table+".csv", index=False, mode="w+")
    
    #status updates
    print(table,"done", sep=" --> ")

circuits --> done
constructor_results --> done
constructor_standings --> done
constructors --> done
driver_standings --> done
driver --> done
lap_times --> done
pit_stops --> done
qualifying --> done
races --> done
results --> done
seasons --> done
status --> done

I could try to figure out how to sort the drivers chronologically and the races as well as I had done before, but I don't think that's actually as important to my analysis.

---

## [02] Getting a "master" table to work with

I'm going to do is create a "master" table with all the relevant columns I think are of interest.

In [3]:
results = pd.read_csv("../data/source/results.csv")

In [4]:
results.head()

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22.0,1,1.0,1,1,10.0,58,1:34:50.616,5690616.0,39.0,2.0,1:27.452,218.300,1
1,2,18,2,2,3.0,5,2.0,2,2,8.0,58,+5.478,5696094.0,41.0,3.0,1:27.739,217.586,1
2,3,18,3,3,7.0,7,3.0,3,3,6.0,58,+8.163,5698779.0,41.0,5.0,1:28.090,216.719,1
3,4,18,4,4,5.0,11,4.0,4,4,5.0,58,+17.181,5707797.0,58.0,7.0,1:28.603,215.464,1
4,5,18,5,1,23.0,3,5.0,5,5,4.0,58,+18.014,5708630.0,43.0,1.0,1:27.418,218.385,1

In [5]:
results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24340 entries, 0 to 24339
Data columns (total 18 columns):
resultId           24340 non-null int64
raceId             24340 non-null int64
driverId           24340 non-null int64
constructorId      24340 non-null int64
number             24334 non-null float64
grid               24340 non-null int64
position           13690 non-null float64
positionText       24340 non-null object
positionOrder      24340 non-null int64
points             24340 non-null float64
laps               24340 non-null int64
time               6269 non-null object
milliseconds       6268 non-null float64
fastestLap         5922 non-null float64
rank               6091 non-null float64
fastestLapTime     5922 non-null object
fastestLapSpeed    5922 non-null float64
statusId           24340 non-null int64
dtypes: float64(7), int64(8), object(3)
memory usage: 3.3+ MB

We're starting with the results table. Columns on this I'm interested in:

* **raceId**: the unique Id for the race
* **driverId**: the unique Id for the driver
* **constructorId**: the unique Id for the constructor(team)
* **grid**: the driver's grid position (where they start the race)
* **position**: the driver's finishing position as an float if the driver finished the race. 
* **positionText**: the driver's finishing position as text. This gives us more information about whether the driver finished or not.  
* **positionOrder**: the driver's finishing position in order from first to last for a given race. Usually the driver who retires first in the race is last and then the orders go up. Ordering takes into account if the driver withdrew, failed to qualify, was excluded from the final positions, or other such situations. 
* **points**: the number of points the driver got. Formula1 has changed the point systems several times since 1950. In this case points are awarded based on the season of the race.
* **status**: information about the driver's finishing position. Wether they finished, retired, withdrew, had a collission, etc. It can also give us information about the car component that went wrong and caused a retirement.

To this subset I want to add more information about the race, the driver and the constructor. I'll begin with the race information.

Before that I'll make a copy of the results table to which I will add things.

In [6]:
master = results[["raceId", "driverId", "constructorId", "grid", "position", "positionText","positionOrder", "points", "statusId"]]

In [7]:
master.head()

,raceId,driverId,constructorId,grid,position,positionText,positionOrder,points,statusId
0,18,1,1,1,1.0,1,1,10.0,1
1,18,2,2,5,2.0,2,2,8.0,1
2,18,3,3,7,3.0,3,3,6.0,1
3,18,4,4,11,4.0,4,4,5.0,1
4,18,5,1,3,5.0,5,5,4.0,1

### Adding more race information

In [8]:
races = pd.read_csv("../data/source/races.csv")

In [9]:
races.head()

,raceId,year,round,circuitId,name,date,time,url
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...

In [10]:
races.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1018 entries, 0 to 1017
Data columns (total 8 columns):
raceId       1018 non-null int64
year         1018 non-null int64
round        1018 non-null int64
circuitId    1018 non-null int64
name         1018 non-null object
date         1018 non-null object
time         287 non-null object
url          1018 non-null object
dtypes: int64(4), object(4)
memory usage: 63.7+ KB

From the races table, I care about the `year`, `round`, `name` columns.

In [11]:
races_slice = races[["raceId", "year", "round", "name"]]

Changing the name of the `name` column so it's more clear that it's the name of the grand prix:

In [12]:
races_slice = races_slice.rename(columns = {"name": "prixName"})

In [13]:
races_slice.head()

   raceId  year  round               prixName
0       1  2009      1  Australian Grand Prix
1       2  2009      2   Malaysian Grand Prix
2       3  2009      3     Chinese Grand Prix
3       4  2009      4     Bahrain Grand Prix
4       5  2009      5     Spanish Grand Prix

I will now add this slice of the race information data to the master table:

In [14]:
master = master.merge(races_slice, on="raceId")

In [15]:
master.head()

,raceId,driverId,constructorId,grid,position,positionText,positionOrder,points,statusId,year,round,prixName
0,18,1,1,1,1.0,1,1,10.0,1,2008,1,Australian Grand Prix
1,18,2,2,5,2.0,2,2,8.0,1,2008,1,Australian Grand Prix
2,18,3,3,7,3.0,3,3,6.0,1,2008,1,Australian Grand Prix
3,18,4,4,11,4.0,4,4,5.0,1,2008,1,Australian Grand Prix
4,18,5,1,3,5.0,5,5,4.0,1,2008,1,Australian Grand Prix

### Adding more driver information

In [16]:
drivers = pd.read_csv("../data/source/driver.csv")

In [17]:
drivers.head()

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44.0,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,NaN,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6.0,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14.0,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,NaN,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

In [18]:
drivers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 847 entries, 0 to 846
Data columns (total 9 columns):
driverId       847 non-null int64
driverRef      847 non-null object
number         44 non-null float64
code           90 non-null object
forename       847 non-null object
surname        847 non-null object
dob            847 non-null object
nationality    847 non-null object
url            846 non-null object
dtypes: float64(1), int64(1), object(7)
memory usage: 59.6+ KB

I'm interested in the `forename`, and `surname` columns.

In [19]:
drivers_slice = drivers[["driverId", "forename", "surname"]]

In [20]:
drivers_slice.head()

   driverId  forename     surname
0         1     Lewis    Hamilton
1         2      Nick    Heidfeld
2         3      Nico     Rosberg
3         4  Fernando      Alonso
4         5    Heikki  Kovalainen

In [21]:
master = master.merge(drivers_slice, on="driverId")

In [22]:
master.head()

,raceId,driverId,constructorId,grid,position,positionText,positionOrder,points,statusId,year,round,prixName,forename,surname
0,18,1,1,1,1.0,1,1,10.0,1,2008,1,Australian Grand Prix,Lewis,Hamilton
1,19,1,1,9,5.0,5,5,4.0,1,2008,2,Malaysian Grand Prix,Lewis,Hamilton
2,20,1,1,3,13.0,13,13,0.0,11,2008,3,Bahrain Grand Prix,Lewis,Hamilton
3,21,1,1,5,3.0,3,3,6.0,1,2008,4,Spanish Grand Prix,Lewis,Hamilton
4,22,1,1,3,2.0,2,2,8.0,1,2008,5,Turkish Grand Prix,Lewis,Hamilton

### Adding constructor information

In [23]:
constructors = pd.read_csv("../data/source/constructors.csv")

In [24]:
constructors.head()

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso

In [25]:
constructors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209 entries, 0 to 208
Data columns (total 5 columns):
constructorId     209 non-null int64
constructorRef    209 non-null object
name              209 non-null object
nationality       209 non-null object
url               209 non-null object
dtypes: int64(1), object(4)
memory usage: 8.2+ KB

For these, I'm interested in both the `constructorRef`, a shortname for each constructor, and the constructor `name`.

In [26]:
constructors_slice = constructors[["constructorId", "constructorRef", "name"]]

Changing the name of the `name` column so it is more clear that it's the name of the constructor

In [27]:
constructors_slice = constructors_slice.rename(columns = {"name": "constructor"})

In [28]:
constructors_slice.head()

   constructorId constructorRef constructor
0              1        mclaren     McLaren
1              2     bmw_sauber  BMW Sauber
2              3       williams    Williams
3              4        renault     Renault
4              5     toro_rosso  Toro Rosso

In [29]:
master = master.merge(constructors_slice, on="constructorId")

In [30]:
master.head()

,raceId,driverId,constructorId,grid,position,positionText,positionOrder,points,statusId,year,round,prixName,forename,surname,constructorRef,constructor
0,18,1,1,1,1.0,1,1,10.0,1,2008,1,Australian Grand Prix,Lewis,Hamilton,mclaren,McLaren
1,19,1,1,9,5.0,5,5,4.0,1,2008,2,Malaysian Grand Prix,Lewis,Hamilton,mclaren,McLaren
2,20,1,1,3,13.0,13,13,0.0,11,2008,3,Bahrain Grand Prix,Lewis,Hamilton,mclaren,McLaren
3,21,1,1,5,3.0,3,3,6.0,1,2008,4,Spanish Grand Prix,Lewis,Hamilton,mclaren,McLaren
4,22,1,1,3,2.0,2,2,8.0,1,2008,5,Turkish Grand Prix,Lewis,Hamilton,mclaren,McLaren

### Adding status information

In [31]:
status = pd.read_csv("../data/source/status.csv")

In [32]:
status.head()

   statusId        status
0         1      Finished
1         2  Disqualified
2         3      Accident
3         4     Collision
4         5        Engine

In [33]:
master = master.merge(status, on="statusId")

In [34]:
master.head()

,raceId,driverId,constructorId,grid,position,positionText,positionOrder,points,statusId,year,round,prixName,forename,surname,constructorRef,constructor,status
0,18,1,1,1,1.0,1,1,10.0,1,2008,1,Australian Grand Prix,Lewis,Hamilton,mclaren,McLaren,Finished
1,19,1,1,9,5.0,5,5,4.0,1,2008,2,Malaysian Grand Prix,Lewis,Hamilton,mclaren,McLaren,Finished
2,21,1,1,5,3.0,3,3,6.0,1,2008,4,Spanish Grand Prix,Lewis,Hamilton,mclaren,McLaren,Finished
3,22,1,1,3,2.0,2,2,8.0,1,2008,5,Turkish Grand Prix,Lewis,Hamilton,mclaren,McLaren,Finished
4,23,1,1,3,1.0,1,1,10.0,1,2008,6,Monaco Grand Prix,Lewis,Hamilton,mclaren,McLaren,Finished

---

Now that my master dataFrame is set, let me rearrange the columns and save it to a csv file to work with in the analysis. Some columnsâ€”`statusId`, `constructorId`â€”are not needed.

In [35]:
master = master[["raceId", "year", "round", "prixName","constructor","constructorRef", "forename", "surname", "grid", "position", "positionText", "positionOrder", "points","status"]]

In [36]:
master.head()

,raceId,year,round,prixName,constructor,constructorRef,forename,surname,grid,position,positionText,positionOrder,points,status
0,18,2008,1,Australian Grand Prix,McLaren,mclaren,Lewis,Hamilton,1,1.0,1,1,10.0,Finished
1,19,2008,2,Malaysian Grand Prix,McLaren,mclaren,Lewis,Hamilton,9,5.0,5,5,4.0,Finished
2,21,2008,4,Spanish Grand Prix,McLaren,mclaren,Lewis,Hamilton,5,3.0,3,3,6.0,Finished
3,22,2008,5,Turkish Grand Prix,McLaren,mclaren,Lewis,Hamilton,3,2.0,2,2,8.0,Finished
4,23,2008,6,Monaco Grand Prix,McLaren,mclaren,Lewis,Hamilton,3,1.0,1,1,10.0,Finished

I'm considering adding some new columns to clarify and combine fields:
1. one that has the full name of the driver `(forename + surname)`
1. one that has the full name of the grand prix `(year + prixName)`

I will leave this for later because it doesn't seem as necessary right now (and I think I can do it when I'm working with D3).

I will go ahead and sort the table by `year` > `round` > `positionOrder` so the first entry is the first position of the first race in 1950 and the last entry is the last position of the most recent race.

In [37]:
master = master.sort_values(by=["year", "round","positionOrder"])

In [38]:
master.head()

,raceId,year,round,prixName,constructor,constructorRef,forename,surname,grid,position,positionText,positionOrder,points,status
3886,833,1950,1,British Grand Prix,Alfa Romeo,alfa,Nino,Farina,1,1.0,1,1,9.0,Finished
3893,833,1950,1,British Grand Prix,Alfa Romeo,alfa,Luigi,Fagioli,2,2.0,2,2,6.0,Finished
3891,833,1950,1,British Grand Prix,Alfa Romeo,alfa,Reg,Parnell,4,3.0,3,3,4.0,Finished
17599,833,1950,1,British Grand Prix,Talbot-Lago,lago,Yves,Cabantous,6,4.0,4,4,3.0,+2 Laps
17596,833,1950,1,British Grand Prix,Talbot-Lago,lago,Louis,Rosier,9,5.0,5,5,2.0,+2 Laps

In [39]:
master.tail()

,raceId,year,round,prixName,constructor,constructorRef,forename,surname,grid,position,positionText,positionOrder,points,status
16219,1016,2019,7,Canadian Grand Prix,Williams,williams,George,Russell,18,16.0,16,16,0.0,+2 Laps
17346,1016,2019,7,Canadian Grand Prix,Haas F1 Team,haas,Kevin,Magnussen,0,17.0,17,17,0.0,+2 Laps
21233,1016,2019,7,Canadian Grand Prix,Williams,williams,Robert,Kubica,19,18.0,18,18,0.0,+3 Laps
16057,1016,2019,7,Canadian Grand Prix,Toro Rosso,toro_rosso,Alexander,Albon,13,NaN,R,19,0.0,Retired
16019,1016,2019,7,Canadian Grand Prix,McLaren,mclaren,Lando,Norris,8,NaN,R,20,0.0,Retired

Ready for saving:

In [40]:
master.to_csv("../data/working/master_results.csv", index=False, mode="w+")

---

## [03] Slicing the master table

I want to create a slice of the master table that only has information from the teams that won the championship. I think this will be a good way to minimize the amount of de-duplication I need to do.

I have a csv file in the `/working` folder of the year and team the championship driver drove for, `championship_teams.csv`

In [41]:
champions = pd.read_csv("../data/working/championship_teams.csv")

In [42]:
champions.head()

   year constructor
0  1950  Alfa Romeo
1  1951  Alfa Romeo
2  1952     Ferrari
3  1953     Ferrari
4  1954    Mercedes

In [43]:
champions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69 entries, 0 to 68
Data columns (total 2 columns):
year           69 non-null int64
constructor    69 non-null object
dtypes: int64(1), object(1)
memory usage: 1.2+ KB

In [44]:
master.head()

,raceId,year,round,prixName,constructor,constructorRef,forename,surname,grid,position,positionText,positionOrder,points,status
3886,833,1950,1,British Grand Prix,Alfa Romeo,alfa,Nino,Farina,1,1.0,1,1,9.0,Finished
3893,833,1950,1,British Grand Prix,Alfa Romeo,alfa,Luigi,Fagioli,2,2.0,2,2,6.0,Finished
3891,833,1950,1,British Grand Prix,Alfa Romeo,alfa,Reg,Parnell,4,3.0,3,3,4.0,Finished
17599,833,1950,1,British Grand Prix,Talbot-Lago,lago,Yves,Cabantous,6,4.0,4,4,3.0,+2 Laps
17596,833,1950,1,British Grand Prix,Talbot-Lago,lago,Louis,Rosier,9,5.0,5,5,2.0,+2 Laps

In [45]:
comparison = pd.merge(master, champions, on=["year","constructor"], how="left", indicator="Winner")

In [46]:
comparison.head()

,raceId,year,round,prixName,constructor,constructorRef,forename,surname,grid,position,positionText,positionOrder,points,status,Winner
0,833,1950,1,British Grand Prix,Alfa Romeo,alfa,Nino,Farina,1,1.0,1,1,9.0,Finished,both
1,833,1950,1,British Grand Prix,Alfa Romeo,alfa,Luigi,Fagioli,2,2.0,2,2,6.0,Finished,both
2,833,1950,1,British Grand Prix,Alfa Romeo,alfa,Reg,Parnell,4,3.0,3,3,4.0,Finished,both
3,833,1950,1,British Grand Prix,Talbot-Lago,lago,Yves,Cabantous,6,4.0,4,4,3.0,+2 Laps,left_only
4,833,1950,1,British Grand Prix,Talbot-Lago,lago,Louis,Rosier,9,5.0,5,5,2.0,+2 Laps,left_only

In [47]:
master_slice = comparison[comparison.Winner == "both"]

In [48]:
master_slice.head(40)

,raceId,year,round,prixName,constructor,constructorRef,forename,surname,grid,position,positionText,positionOrder,points,status,Winner
0,833,1950,1,British Grand Prix,Alfa Romeo,alfa,Nino,Farina,1,1.0,1,1,9.0,Finished,both
1,833,1950,1,British Grand Prix,Alfa Romeo,alfa,Luigi,Fagioli,2,2.0,2,2,6.0,Finished,both
2,833,1950,1,British Grand Prix,Alfa Romeo,alfa,Reg,Parnell,4,3.0,3,3,4.0,Finished,both
12,833,1950,1,British Grand Prix,Alfa Romeo,alfa,Juan,Fangio,3,NaN,R,12,0.0,Oil leak,both
23,834,1950,2,Monaco Grand Prix,Alfa Romeo,alfa,Juan,Fangio,1,1.0,1,1,9.0,Finished,both
33,834,1950,2,Monaco Grand Prix,Alfa Romeo,alfa,Nino,Farina,2,NaN,R,11,0.0,Accident,both
34,834,1950,2,Monaco Grand Prix,Alfa Romeo,alfa,Luigi,Fagioli,5,NaN,R,12,0.0,Accident,both
79,836,1950,4,Swiss Grand Prix,Alfa Romeo,alfa,Nino,Farina,2,1.0,1,1,9.0,Finished,both
80,836,1950,4,Swiss Grand Prix,Alfa Romeo,alfa,Luigi,Fagioli,3,2.0,2,2,6.0,Finished,both
90,836,1950,4,Swiss Grand Prix,Alfa Romeo,alfa,Juan,Fangio,1,NaN,R,12,0.0,Engine,both
97,837,1950,5,Belgian Grand Prix,Alfa Romeo,alfa,Juan,Fangio,2,1.0,1,1,8.0,Finished,both
98,837,1950,5,Belgian Grand Prix,Alfa Romeo,alfa,Luigi,Fagioli,3,2.0,2,2,6.0,Finished,both
100,837,1950,5,Belgian Grand Prix,Alfa Romeo,alfa,Nino,Farina,1,4.0,4,4,4.0,Finished,both
111,838,1950,6,French Grand Prix,Alfa Romeo,alfa,Juan,Fangio,1,1.0,1,1,9.0,Finished,both
112,838,1950,6,French Grand Prix,Alfa Romeo,alfa,Luigi,Fagioli,3,2.0,2,2,6.0,Finished,both
119,838,1950,6,French Grand Prix,Alfa Romeo,alfa,Nino,Farina,2,7.0,7,7,0.0,Fuel pump,both
131,839,1950,7,Italian Grand Prix,Alfa Romeo,alfa,Nino,Farina,3,1.0,1,1,8.0,Finished,both
133,839,1950,7,Italian Grand Prix,Alfa Romeo,alfa,Alberto,Ascari,6,2.0,2,2,3.0,Finished,both
134,839,1950,7,Italian Grand Prix,Alfa Romeo,alfa,Luigi,Fagioli,5,3.0,3,3,4.0,Finished,both
144,839,1950,7,Italian Grand Prix,Alfa Romeo,alfa,Juan,Fangio,7,NaN,R,13,0.0,Engine,both
145,839,1950,7,Italian Grand Prix,Alfa Romeo,alfa,Piero,Taruffi,7,NaN,R,13,0.0,Engine,both
147,839,1950,7,Italian Grand Prix,Alfa Romeo,alfa,Juan,Fangio,1,NaN,R,15,1.0,Gearbox,both
155,839,1950,7,Italian Grand Prix,Alfa Romeo,alfa,Consalvo,Sanesi,4,NaN,R,23,0.0,Engine,both
160,825,1951,1,Swiss Grand Prix,Alfa Romeo,alfa,Juan,Fangio,1,1.0,1,1,9.0,Finished,both
162,825,1951,1,Swiss Grand Prix,Alfa Romeo,alfa,Nino,Farina,2,3.0,3,3,4.0,Finished,both
163,825,1951,1,Swiss Grand Prix,Alfa Romeo,alfa,Consalvo,Sanesi,4,4.0,4,4,3.0,+1 Lap,both
164,825,1951,1,Swiss Grand Prix,Alfa Romeo,alfa,Toulo,de Graffenried,5,5.0,5,5,2.0,+2 Laps,both
215,827,1951,3,Belgian Grand Prix,Alfa Romeo,alfa,Nino,Farina,2,1.0,1,1,8.0,Finished,both
223,827,1951,3,Belgian Grand Prix,Alfa Romeo,alfa,Juan,Fangio,1,9.0,9,9,1.0,+4 Laps,both
225,827,1951,3,Belgian Grand Prix,Alfa Romeo,alfa,Consalvo,Sanesi,6,NaN,R,11,0.0,Radiator,both
228,828,1951,4,French Grand Prix,Alfa Romeo,alfa,Juan,Fangio,7,1.0,1,1,5.0,Finished,both
229,828,1951,4,French Grand Prix,Alfa Romeo,alfa,Luigi,Fagioli,7,1.0,1,1,4.0,Finished,both
234,828,1951,4,French Grand Prix,Alfa Romeo,alfa,Nino,Farina,2,5.0,5,5,2.0,+4 Laps,both
239,828,1951,4,French Grand Prix,Alfa Romeo,alfa,Consalvo,Sanesi,5,10.0,10,10,0.0,+19 Laps,both
240,828,1951,4,French Grand Prix,Alfa Romeo,alfa,Juan,Fangio,1,11.0,11,11,0.0,+22 Laps,both
241,828,1951,4,French Grand Prix,Alfa Romeo,alfa,Luigi,Fagioli,1,11.0,11,11,0.0,+22 Laps,both
255,829,1951,5,British Grand Prix,Alfa Romeo,alfa,Juan,Fangio,2,2.0,2,2,6.0,Finished,both
257,829,1951,5,British Grand Prix,Alfa Romeo,alfa,Felice,Bonetto,7,4.0,4,4,3.0,+3 Laps,both
259,829,1951,5,British Grand Prix,Alfa Romeo,alfa,Consalvo,Sanesi,6,6.0,6,6,0.0,+6 Laps,both
267,829,1951,5,British Grand Prix,Alfa Romeo,alfa,Nino,Farina,3,NaN,R,14,1.0,Clutch,both

In [49]:
master_slice.tail(42)

,raceId,year,round,prixName,constructor,constructorRef,forename,surname,grid,position,positionText,positionOrder,points,status,Winner
23781,989,2018,1,Australian Grand Prix,Mercedes,mercedes,Lewis,Hamilton,1,2.0,2,2,18.0,Finished,both
23787,989,2018,1,Australian Grand Prix,Mercedes,mercedes,Valtteri,Bottas,15,8.0,8,8,4.0,Finished,both
23801,990,2018,2,Bahrain Grand Prix,Mercedes,mercedes,Valtteri,Bottas,3,2.0,2,2,18.0,Finished,both
23802,990,2018,2,Bahrain Grand Prix,Mercedes,mercedes,Lewis,Hamilton,9,3.0,3,3,15.0,Finished,both
23821,991,2018,3,Chinese Grand Prix,Mercedes,mercedes,Valtteri,Bottas,3,2.0,2,2,18.0,Finished,both
23823,991,2018,3,Chinese Grand Prix,Mercedes,mercedes,Lewis,Hamilton,4,4.0,4,4,12.0,Finished,both
23840,992,2018,4,Azerbaijan Grand Prix,Mercedes,mercedes,Lewis,Hamilton,2,1.0,1,1,25.0,Finished,both
23853,992,2018,4,Azerbaijan Grand Prix,Mercedes,mercedes,Valtteri,Bottas,3,NaN,R,14,0.0,Puncture,both
23860,993,2018,5,Spanish Grand Prix,Mercedes,mercedes,Lewis,Hamilton,1,1.0,1,1,25.0,Finished,both
23861,993,2018,5,Spanish Grand Prix,Mercedes,mercedes,Valtteri,Bottas,2,2.0,2,2,18.0,Finished,both
23882,994,2018,6,Monaco Grand Prix,Mercedes,mercedes,Lewis,Hamilton,3,3.0,3,3,15.0,Finished,both
23884,994,2018,6,Monaco Grand Prix,Mercedes,mercedes,Valtteri,Bottas,5,5.0,5,5,10.0,Finished,both
23901,995,2018,7,Canadian Grand Prix,Mercedes,mercedes,Valtteri,Bottas,2,2.0,2,2,18.0,Finished,both
23904,995,2018,7,Canadian Grand Prix,Mercedes,mercedes,Lewis,Hamilton,4,5.0,5,5,10.0,Finished,both
23920,996,2018,8,French Grand Prix,Mercedes,mercedes,Lewis,Hamilton,1,1.0,1,1,25.0,Finished,both
23926,996,2018,8,French Grand Prix,Mercedes,mercedes,Valtteri,Bottas,2,7.0,7,7,6.0,Finished,both
23955,997,2018,9,Austrian Grand Prix,Mercedes,mercedes,Lewis,Hamilton,2,NaN,R,16,0.0,Fuel pressure,both
23958,997,2018,9,Austrian Grand Prix,Mercedes,mercedes,Valtteri,Bottas,1,NaN,R,19,0.0,Hydraulics,both
23961,998,2018,10,British Grand Prix,Mercedes,mercedes,Lewis,Hamilton,1,2.0,2,2,18.0,Finished,both
23963,998,2018,10,British Grand Prix,Mercedes,mercedes,Valtteri,Bottas,4,4.0,4,4,12.0,Finished,both
23980,999,2018,11,German Grand Prix,Mercedes,mercedes,Lewis,Hamilton,14,1.0,1,1,25.0,Finished,both
23981,999,2018,11,German Grand Prix,Mercedes,mercedes,Valtteri,Bottas,2,2.0,2,2,18.0,Finished,both
24000,1000,2018,12,Hungarian Grand Prix,Mercedes,mercedes,Lewis,Hamilton,1,1.0,1,1,25.0,Finished,both
24004,1000,2018,12,Hungarian Grand Prix,Mercedes,mercedes,Valtteri,Bottas,2,5.0,5,5,10.0,Finished,both
24021,1001,2018,13,Belgian Grand Prix,Mercedes,mercedes,Lewis,Hamilton,1,2.0,2,2,18.0,Finished,both
24023,1001,2018,13,Belgian Grand Prix,Mercedes,mercedes,Valtteri,Bottas,19,4.0,4,4,12.0,Finished,both
24040,1002,2018,14,Italian Grand Prix,Mercedes,mercedes,Lewis,Hamilton,3,1.0,1,1,25.0,Finished,both
24042,1002,2018,14,Italian Grand Prix,Mercedes,mercedes,Valtteri,Bottas,4,3.0,3,3,15.0,Finished,both
24060,1003,2018,15,Singapore Grand Prix,Mercedes,mercedes,Lewis,Hamilton,1,1.0,1,1,25.0,Finished,both
24063,1003,2018,15,Singapore Grand Prix,Mercedes,mercedes,Valtteri,Bottas,4,4.0,4,4,12.0,Finished,both
24080,1004,2018,16,Russian Grand Prix,Mercedes,mercedes,Lewis,Hamilton,2,1.0,1,1,25.0,Finished,both
24081,1004,2018,16,Russian Grand Prix,Mercedes,mercedes,Valtteri,Bottas,1,2.0,2,2,18.0,Finished,both
24100,1005,2018,17,Japanese Grand Prix,Mercedes,mercedes,Lewis,Hamilton,1,1.0,1,1,25.0,Finished,both
24101,1005,2018,17,Japanese Grand Prix,Mercedes,mercedes,Valtteri,Bottas,2,2.0,2,2,18.0,Finished,both
24122,1006,2018,18,United States Grand Prix,Mercedes,mercedes,Lewis,Hamilton,1,3.0,3,3,15.0,Finished,both
24124,1006,2018,18,United States Grand Prix,Mercedes,mercedes,Valtteri,Bottas,3,5.0,5,5,10.0,Finished,both
24143,1007,2018,19,Mexican Grand Prix,Mercedes,mercedes,Lewis,Hamilton,3,4.0,4,4,12.0,Finished,both
24144,1007,2018,19,Mexican Grand Prix,Mercedes,mercedes,Valtteri,Bottas,5,5.0,5,5,10.0,+1 Lap,both
24160,1008,2018,20,Brazilian Grand Prix,Mercedes,mercedes,Lewis,Hamilton,1,1.0,1,1,25.0,Finished,both
24164,1008,2018,20,Brazilian Grand Prix,Mercedes,mercedes,Valtteri,Bottas,3,5.0,5,5,10.0,Finished,both
24180,1009,2018,21,Abu Dhabi Grand Prix,Mercedes,mercedes,Lewis,Hamilton,1,1.0,1,1,25.0,Finished,both
24184,1009,2018,21,Abu Dhabi Grand Prix,Mercedes,mercedes,Valtteri,Bottas,2,5.0,5,5,10.0,Finished,both

This slice looks good. Let's drop the `Winner` column used for comparison.

In [50]:
master_slice = master_slice.drop(columns=["Winner"])

In [51]:
master_slice.head()

,raceId,year,round,prixName,constructor,constructorRef,forename,surname,grid,position,positionText,positionOrder,points,status
0,833,1950,1,British Grand Prix,Alfa Romeo,alfa,Nino,Farina,1,1.0,1,1,9.0,Finished
1,833,1950,1,British Grand Prix,Alfa Romeo,alfa,Luigi,Fagioli,2,2.0,2,2,6.0,Finished
2,833,1950,1,British Grand Prix,Alfa Romeo,alfa,Reg,Parnell,4,3.0,3,3,4.0,Finished
12,833,1950,1,British Grand Prix,Alfa Romeo,alfa,Juan,Fangio,3,NaN,R,12,0.0,Oil leak
23,834,1950,2,Monaco Grand Prix,Alfa Romeo,alfa,Juan,Fangio,1,1.0,1,1,9.0,Finished

In [52]:
master_slice.to_csv("../data/working/master_results_champions.csv", index=False, mode="w+")

---

## [04] Removing driver info

When handling some of the early races, there were instances of drivers sharing or switching cars and then sharing finishes (they split the points). Let me see if I remove that and keep just the position, and team information in a separate set of dataFrames.

In [53]:
master.head()

,raceId,year,round,prixName,constructor,constructorRef,forename,surname,grid,position,positionText,positionOrder,points,status
3886,833,1950,1,British Grand Prix,Alfa Romeo,alfa,Nino,Farina,1,1.0,1,1,9.0,Finished
3893,833,1950,1,British Grand Prix,Alfa Romeo,alfa,Luigi,Fagioli,2,2.0,2,2,6.0,Finished
3891,833,1950,1,British Grand Prix,Alfa Romeo,alfa,Reg,Parnell,4,3.0,3,3,4.0,Finished
17599,833,1950,1,British Grand Prix,Talbot-Lago,lago,Yves,Cabantous,6,4.0,4,4,3.0,+2 Laps
17596,833,1950,1,British Grand Prix,Talbot-Lago,lago,Louis,Rosier,9,5.0,5,5,2.0,+2 Laps

Looking at master, I want to remove the `forename`, `surname`, `grid`, `points`, `status` columns

In [54]:
master_noDriver = master.copy().drop(columns=["forename", "surname", "grid", "points", "status"])

In [55]:
master_noDriver.head()

,raceId,year,round,prixName,constructor,constructorRef,position,positionText,positionOrder
3886,833,1950,1,British Grand Prix,Alfa Romeo,alfa,1.0,1,1
3893,833,1950,1,British Grand Prix,Alfa Romeo,alfa,2.0,2,2
3891,833,1950,1,British Grand Prix,Alfa Romeo,alfa,3.0,3,3
17599,833,1950,1,British Grand Prix,Talbot-Lago,lago,4.0,4,4
17596,833,1950,1,British Grand Prix,Talbot-Lago,lago,5.0,5,5

I will also do this to the slice of the master results for the championship teams:

In [56]:
master_slice_noDriver = master_slice.copy().drop(columns=["forename", "surname", "grid", "points", "status"])

In [57]:
master_slice_noDriver.head()

,raceId,year,round,prixName,constructor,constructorRef,position,positionText,positionOrder
0,833,1950,1,British Grand Prix,Alfa Romeo,alfa,1.0,1,1
1,833,1950,1,British Grand Prix,Alfa Romeo,alfa,2.0,2,2
2,833,1950,1,British Grand Prix,Alfa Romeo,alfa,3.0,3,3
12,833,1950,1,British Grand Prix,Alfa Romeo,alfa,NaN,R,12
23,834,1950,2,Monaco Grand Prix,Alfa Romeo,alfa,1.0,1,1

I will take the moment to also look at the duplicates in these two.

### [04.5] Cleaning duplicates

Let's look at `master_noDriver` and `master_slice_noDriver` and try to clean the duplicates.

In [58]:
master_slice_noDriver.head()

,raceId,year,round,prixName,constructor,constructorRef,position,positionText,positionOrder
0,833,1950,1,British Grand Prix,Alfa Romeo,alfa,1.0,1,1
1,833,1950,1,British Grand Prix,Alfa Romeo,alfa,2.0,2,2
2,833,1950,1,British Grand Prix,Alfa Romeo,alfa,3.0,3,3
12,833,1950,1,British Grand Prix,Alfa Romeo,alfa,NaN,R,12
23,834,1950,2,Monaco Grand Prix,Alfa Romeo,alfa,1.0,1,1

In [59]:
master_slice_noDriver.duplicated().value_counts()

False    2350
True       21
dtype: int64

It seems like there are 21 lines that are duplicated. Let's check them out

In [60]:
a = master_slice_noDriver.copy()

In [61]:
a["Duplicate"] = a.duplicated(keep=False).map({True:'Yes', False:'No'})

In [62]:
a.head(30)

,raceId,year,round,prixName,constructor,constructorRef,position,positionText,positionOrder,Duplicate
0,833,1950,1,British Grand Prix,Alfa Romeo,alfa,1.0,1,1,No
1,833,1950,1,British Grand Prix,Alfa Romeo,alfa,2.0,2,2,No
2,833,1950,1,British Grand Prix,Alfa Romeo,alfa,3.0,3,3,No
12,833,1950,1,British Grand Prix,Alfa Romeo,alfa,NaN,R,12,No
23,834,1950,2,Monaco Grand Prix,Alfa Romeo,alfa,1.0,1,1,No
33,834,1950,2,Monaco Grand Prix,Alfa Romeo,alfa,NaN,R,11,No
34,834,1950,2,Monaco Grand Prix,Alfa Romeo,alfa,NaN,R,12,No
79,836,1950,4,Swiss Grand Prix,Alfa Romeo,alfa,1.0,1,1,No
80,836,1950,4,Swiss Grand Prix,Alfa Romeo,alfa,2.0,2,2,No
90,836,1950,4,Swiss Grand Prix,Alfa Romeo,alfa,NaN,R,12,No
97,837,1950,5,Belgian Grand Prix,Alfa Romeo,alfa,1.0,1,1,No
98,837,1950,5,Belgian Grand Prix,Alfa Romeo,alfa,2.0,2,2,No
100,837,1950,5,Belgian Grand Prix,Alfa Romeo,alfa,4.0,4,4,No
111,838,1950,6,French Grand Prix,Alfa Romeo,alfa,1.0,1,1,No
112,838,1950,6,French Grand Prix,Alfa Romeo,alfa,2.0,2,2,No
119,838,1950,6,French Grand Prix,Alfa Romeo,alfa,7.0,7,7,No
131,839,1950,7,Italian Grand Prix,Alfa Romeo,alfa,1.0,1,1,No
133,839,1950,7,Italian Grand Prix,Alfa Romeo,alfa,2.0,2,2,No
134,839,1950,7,Italian Grand Prix,Alfa Romeo,alfa,3.0,3,3,No
144,839,1950,7,Italian Grand Prix,Alfa Romeo,alfa,NaN,R,13,Yes
145,839,1950,7,Italian Grand Prix,Alfa Romeo,alfa,NaN,R,13,Yes
147,839,1950,7,Italian Grand Prix,Alfa Romeo,alfa,NaN,R,15,No
155,839,1950,7,Italian Grand Prix,Alfa Romeo,alfa,NaN,R,23,No
160,825,1951,1,Swiss Grand Prix,Alfa Romeo,alfa,1.0,1,1,No
162,825,1951,1,Swiss Grand Prix,Alfa Romeo,alfa,3.0,3,3,No
163,825,1951,1,Swiss Grand Prix,Alfa Romeo,alfa,4.0,4,4,No
164,825,1951,1,Swiss Grand Prix,Alfa Romeo,alfa,5.0,5,5,No
215,827,1951,3,Belgian Grand Prix,Alfa Romeo,alfa,1.0,1,1,No
223,827,1951,3,Belgian Grand Prix,Alfa Romeo,alfa,9.0,9,9,No
225,827,1951,3,Belgian Grand Prix,Alfa Romeo,alfa,NaN,R,11,No

In [63]:
a[a.Duplicate == "Yes"]

,raceId,year,round,prixName,constructor,constructorRef,position,positionText,positionOrder,Duplicate
144,839,1950,7,Italian Grand Prix,Alfa Romeo,alfa,NaN,R,13,Yes
145,839,1950,7,Italian Grand Prix,Alfa Romeo,alfa,NaN,R,13,Yes
228,828,1951,4,French Grand Prix,Alfa Romeo,alfa,1.0,1,1,Yes
229,828,1951,4,French Grand Prix,Alfa Romeo,alfa,1.0,1,1,Yes
240,828,1951,4,French Grand Prix,Alfa Romeo,alfa,11.0,11,11,Yes
241,828,1951,4,French Grand Prix,Alfa Romeo,alfa,11.0,11,11,Yes
298,831,1951,7,Italian Grand Prix,Alfa Romeo,alfa,3.0,3,3,Yes
299,831,1951,7,Italian Grand Prix,Alfa Romeo,alfa,3.0,3,3,Yes
348,817,1952,1,Swiss Grand Prix,Ferrari,ferrari,NaN,R,10,Yes
349,817,1952,1,Swiss Grand Prix,Ferrari,ferrari,NaN,R,10,Yes
426,820,1952,4,French Grand Prix,Ferrari,ferrari,11.0,11,11,Yes
427,820,1952,4,French Grand Prix,Ferrari,ferrari,11.0,11,11,Yes
718,814,1953,7,German Grand Prix,Ferrari,ferrari,8.0,8,8,Yes
719,814,1953,7,German Grand Prix,Ferrari,ferrari,8.0,8,8,Yes
728,814,1953,7,German Grand Prix,Ferrari,ferrari,NaN,R,17,Yes
729,814,1953,7,German Grand Prix,Ferrari,ferrari,NaN,R,17,Yes
1037,792,1955,1,Argentine Grand Prix,Mercedes,mercedes,4.0,4,4,Yes
1038,792,1955,1,Argentine Grand Prix,Mercedes,mercedes,4.0,4,4,Yes
1039,792,1955,1,Argentine Grand Prix,Mercedes,mercedes,4.0,4,4,Yes
1210,784,1956,1,Argentine Grand Prix,Ferrari,ferrari,1.0,1,1,Yes
1211,784,1956,1,Argentine Grand Prix,Ferrari,ferrari,1.0,1,1,Yes
1227,785,1956,2,Monaco Grand Prix,Ferrari,ferrari,2.0,2,2,Yes
1228,785,1956,2,Monaco Grand Prix,Ferrari,ferrari,2.0,2,2,Yes
1230,785,1956,2,Monaco Grand Prix,Ferrari,ferrari,4.0,4,4,Yes
1231,785,1956,2,Monaco Grand Prix,Ferrari,ferrari,4.0,4,4,Yes
1320,789,1956,6,British Grand Prix,Ferrari,ferrari,2.0,2,2,Yes
1321,789,1956,6,British Grand Prix,Ferrari,ferrari,2.0,2,2,Yes
1329,789,1956,6,British Grand Prix,Ferrari,ferrari,10.0,10,10,Yes
1330,789,1956,6,British Grand Prix,Ferrari,ferrari,10.0,10,10,Yes
1372,791,1956,8,Italian Grand Prix,Ferrari,ferrari,2.0,2,2,Yes
1373,791,1956,8,Italian Grand Prix,Ferrari,ferrari,2.0,2,2,Yes
1379,791,1956,8,Italian Grand Prix,Ferrari,ferrari,8.0,8,8,Yes
1380,791,1956,8,Italian Grand Prix,Ferrari,ferrari,8.0,8,8,Yes
1425,777,1957,2,Monaco Grand Prix,Maserati,maserati,NaN,R,8,Yes
1426,777,1957,2,Monaco Grand Prix,Maserati,maserati,NaN,R,8,Yes
1555,783,1957,8,Italian Grand Prix,Maserati,maserati,5.0,5,5,Yes
1556,783,1957,8,Italian Grand Prix,Maserati,maserati,5.0,5,5,Yes
1562,783,1957,8,Italian Grand Prix,Maserati,maserati,11.0,11,11,Yes
1563,783,1957,8,Italian Grand Prix,Maserati,maserati,11.0,11,11,Yes
2009,746,1960,1,Argentine Grand Prix,Cooper-Climax,cooper-climax,3.0,3,3,Yes
2010,746,1960,1,Argentine Grand Prix,Cooper-Climax,cooper-climax,3.0,3,3,Yes

In [64]:
a[a.Duplicate == "Yes"].shape

(41, 10)